### ISSUE TITLE
Feat: Support `application/x-www-form-urlencoded` request bodies

### ISSUE THREAD

**Issue by ryan-mars** [jlalmes/trpc-openapi#187] opened 2022-11-30 23:12 UTC
I would like to migrate a legacy REST API with an OpenAPI spec to TRPC. In order to do so we must accept `application/x-www-form-urlencoded` request bodies.

**Comment by KATT** [comment] 2022-11-30 23:56
Slight duplicate of #58 but I've been meaning to separate "form data" & "transport types".

Question for you, @ryan-mars: is it fine that the procedure would return JSON? Is this only for the "input"?

**Comment by KATT** [comment] 2022-11-30 23:56
Oops, I was mixing up repos. I was thinking this was on trpc :)

**Comment by jlalmes** [comment] 2022-12-01 12:46
Hi @ryan-mars thank for opening this issue! This seems pretty straightforward to implement, can you share a link/example OpenAPI schema that I can prototype against?

**Comment by ryan-mars** [comment] 2022-12-09 21:26
> can you share a link/example OpenAPI schema that I can prototype against?

```yaml
openapi: 3.0.0
info:
  version: "1.0.0"
  title: "OAuth 2.0 Example"

  description: "OAuth 2.0 Example"

servers:
  - url: "https://localhost:3000"

tags:
  - name: Token Management
    description: Get tokens

paths:
  /token:
    post:
      operationId: oauthToken
      description: Request a new access token.
      tags:
        - Token Management
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: "#/components/schemas/ClientCredentialsTokenRequest"
      responses:
        "200":
          description: New access token generated.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TokenResponse"
        "400":
          description: Some parameters were invalid.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TokenErrorResponse"
components:
  schemas:
    ClientIdentification:
      type: string
      description: client ID
      example: A771A1923BD403603831A2425DF818A4
    ClientCredentialsTokenRequest:
      type: object
      required:
        - client_id
        - grant_type
      properties:
        client_id:
          $ref: "#/components/schemas/ClientIdentification"
        grant_type:
          type: string
          enum:
            - client_credentials
        scope:
          type: string
      additionalProperties: false
    TokenResponse:
      type: object
      required:
        - access_token
        - token_type
      properties:
        access_token:
          type: string
        token_type:
          type: string
          enum:
            - bearer
        expires_in:
          type: number

        refresh_token:
          type: string

        scope:
          type: string

    TokenErrorResponse:
      type: object
      required:
        - error
      properties:
        error:
          type: string
          enum:
            - invalid_request
            - invalid_client
            - invalid_grant
            - unauthorized_client
            - unsupported_grant_type
            - invalid_scope
        error_description:
          type: string
        error_uri:
          type: string
```

**Comment by harveylee** [comment] 2022-12-22 05:25
I ran into this and worked around with a middleware, something like this:

```ts
import { retrieveToken } from '@fleetseer/server-utils'
import { inferAsyncReturnType, initTRPC, TRPCError } from '@trpc/server'
import * as trpcExpress from '@trpc/server/adapters/express'
import { z } from 'zod'
import { OpenApiMeta } from 'trpc-openapi'
import { urlencoded } from 'express'

export function createContext (options: trpcExpress.CreateExpressContextOptions) {
  return {
    express: options
  }
}
type Context = inferAsyncReturnType<typeof createContext>
export const t = initTRPC.meta<OpenApiMeta>().context<Context>().create()

const decode = urlencoded({ extended: false })
const postMethod = t.procedure
  .use(t.middleware(async ({ ctx, next, rawInput }) => {
    await new Promise<void>((resolve, reject) => {
      decode(ctx.express.req, ctx.express.res, (err) => {
        if (err != null) {
          reject(new TRPCError({ code: 'BAD_REQUEST', message: 'Content-Type should be application/x-www-form-urlencoded' }))
        }
        Object.assign(rawInput as object, ctx.express.req.body)
        resolve()
      })
    })
    return await next()
  }))
  .meta({
    openapi: {
      method: 'POST',
      path: '/my-post-method'
    }
  })
  .input(z.object({
    foo: z.string()
  }))
  .output(z.object({
    bar: z.string()
  }))
  .mutation(async ({ input }) => {
    // ... input.foo is a string
  })
```

**Closed** 2023-01-02 23:37 UTC
Labels: enhancement
